import React, { useState, useEffect, useRef, useCallback } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { useSanctuaryStore } from "../store/useSanctuaryStore.js";

const BG_SRC = "/assets/SanctuaryStorybook.webp";

// Minimal chapter skeleton — content will be generated by AI at runtime
const CHAPTERS = Array.from({ length: 5 }, (_, i) => ({
  id: i + 1,
  week: i + 1,
  title: `Chapter ${i + 1}`,
  subtitle: "",
  emblem: "",
  paragraphs: [],
  quote: "",
}));

// ─── Fireflies ────────────────────────────────────────────────────────────────
function Fireflies({ count = 12 }) {
  const flies = useRef(
    Array.from({ length: count }, (_, i) => ({
      id: i,
      x: Math.random() * 100,
      y: Math.random() * 70,
      size: Math.random() * 3 + 1.5,
      delay: Math.random() * 6,
      dur: Math.random() * 5 + 5,
      dx: (Math.random() - 0.5) * 80,
      dy: (Math.random() - 0.5) * 50,
    }))
  ).current;
  return (
    <div style={{ position: "absolute", inset: 0, pointerEvents: "none", overflow: "hidden" }}>
      {flies.map((f) => (
        <div key={f.id} style={{
          position: "absolute", left: `${f.x}%`, top: `${f.y}%`,
          width: f.size, height: f.size, borderRadius: "50%",
          background: "#c8e89a",
          boxShadow: "0 0 7px 3px rgba(200,232,154,0.7)",
          animation: `ffDrift ${f.dur}s ${f.delay}s ease-in-out infinite alternate, ffBlink ${f.dur * 0.6}s ${f.delay}s ease-in-out infinite`,
          "--fdx": `${f.dx}px`, "--fdy": `${f.dy}px`,
        }} />
      ))}
    </div>
  );
}

function OrnamentDivider({ color = "#8a6a3a" }) {
  return (
    <svg width="100" height="10" viewBox="0 0 100 10" fill="none" style={{ display: "block", margin: "0 auto", opacity: 0.65 }}>
      <line x1="0" y1="5" x2="38" y2="5" stroke={color} strokeWidth="0.8" />
      <circle cx="44" cy="5" r="2" fill={color} />
      <circle cx="50" cy="5" r="2.5" fill={color} />
      <circle cx="56" cy="5" r="2" fill={color} />
      <line x1="62" y1="5" x2="100" y2="5" stroke={color} strokeWidth="0.8" />
    </svg>
  );
}

// ─── Main ─────────────────────────────────────────────────────────────────────
export default function StorybookScreen() {
  const navigate = useNavigate();
  const location = useLocation();
  const { logs, generateStory } = useSanctuaryStore();

  // Determine initial chapter from Chronicle navigation state
  const getInitialIndex = () => {
    const state = location.state?.chapter;
    if (!state) return 0;
    const idx = CHAPTERS.findIndex(
      (c) => c.week === state.week || c.title === state.title
    );
    return idx >= 0 ? idx : 0;
  };

  const [currentIndex, setCurrentIndex] = useState(getInitialIndex);
  const [flipping, setFlipping] = useState(false);
  const [aiStories, setAiStories] = useState({});
  const [generatingId, setGeneratingId] = useState(null);
  const flipTimeout = useRef(null);

  const chapter = CHAPTERS[currentIndex];
  const aiParagraphs = aiStories[chapter?.id];
  const isGenerating = generatingId === chapter?.id;
  const displayParagraphs = aiParagraphs || chapter?.paragraphs || [];

  // Auto-generate when enough logs
  useEffect(() => {
    // Generate the full story once and split into chapters when logs are sufficient.
    const shouldGenerate = logs.length >= 3 && Object.keys(aiStories).length === 0 && !generatingId;
    if (shouldGenerate) {
      (async () => {
        setGeneratingId('all');
        try {
          const story = await generateStory();
          if (story) {
            const text = typeof story === 'string' ? story : story.story || story.narration || story.chronicle || '';
            const paras = text.split(/\n+/).map(p => p.trim()).filter(p => p.length > 0);
            const perChap = Math.max(1, Math.floor(paras.length / CHAPTERS.length));
            const newAi = {};
            CHAPTERS.forEach((c, idx) => {
              const offset = idx * perChap;
              const chapterParas = paras.slice(offset, offset + perChap);
              newAi[c.id] = chapterParas.length > 0 ? chapterParas : ["A quiet memory waits here."];
            });
            setAiStories(newAi);
            // Optionally set generated titles from first sentence of each chapter
            // (keep existing `title` if generation yields nothing)
            setTimeout(() => {
              CHAPTERS.forEach((c) => {
                const g = newAi[c.id];
                if (g && g[0]) {
                  c.title = g[0].split(/[.?!]/)[0].slice(0, 36);
                }
              });
            }, 0);
          }
        } catch {
          // fall back gracefully to static chapters (none present)
        } finally {
          setGeneratingId(null);
        }
      })();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [chapter?.id]);

  const handleGenerate = useCallback(async () => {
    if (!chapter || generatingId === chapter.id) return;
    setGeneratingId(chapter.id);
    try {
      const story = await generateStory();
      if (story) {
        const paras = story.split(/\n+/).filter((p) => p.trim().length > 0);
        const perChap = Math.max(2, Math.floor(paras.length / CHAPTERS.length));
        const offset = currentIndex * perChap;
        const chapterParas = paras.slice(offset, offset + perChap);
        setAiStories((prev) => ({
          ...prev,
          [chapter.id]: chapterParas.length > 0 ? chapterParas : chapter.paragraphs,
        }));
      }
    } catch {
      // fall back to static
    } finally {
      setGeneratingId(null);
    }
  }, [chapter, currentIndex, generatingId, generateStory]);

  const triggerFlip = useCallback((newIndex) => {
    if (flipping) return;
    setFlipping(true);
    flipTimeout.current = setTimeout(() => {
      setCurrentIndex(newIndex);
      setFlipping(false);
    }, 300);
  }, [flipping]);

  useEffect(() => () => clearTimeout(flipTimeout.current), []);

  useEffect(() => {
    const handler = (e) => {
      if (e.key === "ArrowLeft" && currentIndex > 0) triggerFlip(currentIndex - 1);
      if (e.key === "ArrowRight" && currentIndex < CHAPTERS.length - 1) triggerFlip(currentIndex + 1);
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [currentIndex, triggerFlip]);

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700&family=Cinzel+Decorative:wght@400;700&family=Lora:ital,wght@0,400;0,600;1,400&display=swap');

        @keyframes ffDrift { from { transform: translate(0,0); } to { transform: translate(var(--fdx), var(--fdy)); } }
        @keyframes ffBlink { 0%,100% { opacity:0.85; } 50% { opacity:0.1; } }
        @keyframes storyDot { 0%,100% { opacity:0.2; transform:translateY(0); } 50% { opacity:1; transform:translateY(-4px); } }
        @keyframes fadeIn { from { opacity:0; transform:translateY(6px); } to { opacity:1; transform:translateY(0); } }
        @keyframes foxSway { 0%,100% { transform:rotate(-2deg) translateY(0); } 50% { transform:rotate(2deg) translateY(-6px); } }

        .sb-page-content { animation: fadeIn 0.4s ease forwards; }
        .sb-root * { box-sizing: border-box; }
      `}</style>

      <div className="sb-root" style={{
        position: "relative", width: "100%", height: "100svh",
        overflow: "hidden", background: "#0a0704",
      }}>

        {/* Background */}
        <img src={BG_SRC} alt="" aria-hidden draggable={false} style={{
          position: "absolute", inset: 0, width: "100%", height: "100%",
          objectFit: "cover", objectPosition: "center",
          userSelect: "none", pointerEvents: "none",
        }} />

        {/* Subtle vignette — keep it light so book pages stay visible */}
        <div aria-hidden style={{
          position: "absolute", inset: 0, pointerEvents: "none",
          background: "radial-gradient(ellipse 100% 80% at 50% 50%, transparent 40%, rgba(0,0,0,0.45) 100%)",
        }} />

        <Fireflies />

        {/* ── Header ── */}
        <header style={{
          position: "absolute", top: 0, left: 0, right: 0,
          display: "grid", gridTemplateColumns: "1fr auto 1fr", alignItems: "center",
          padding: "14px 20px", zIndex: 30,
        }}>
          <button onClick={() => navigate("/chronicle")} style={{
            background: "rgba(12,8,2,0.72)", border: "1px solid rgba(200,168,75,0.35)",
            borderRadius: 50, color: "#c8a84b",
            fontFamily: "'Cinzel', serif", fontSize: "0.68rem", letterSpacing: "0.1em",
            padding: "6px 14px", cursor: "pointer", backdropFilter: "blur(4px)",
            display: "flex", alignItems: "center", gap: 5,
          }}>
            ← Back
          </button>

          <div style={{
            fontFamily: "'Cinzel Decorative', serif", fontSize: "clamp(0.75rem, 2vw, 1rem)",
            color: "#f0e0b0", letterSpacing: "0.12em",
            textShadow: "0 0 14px rgba(200,168,75,0.6)",
            textAlign: "center",
          }}>
            Sanctuary Storybook
          </div>

          <div style={{
            background: "rgba(12,8,2,0.72)", border: "1px solid rgba(200,168,75,0.35)",
            borderRadius: 50, color: "#c8a84b",
            fontFamily: "'Cinzel', serif", fontSize: "0.62rem", letterSpacing: "0.1em",
            padding: "6px 14px", backdropFilter: "blur(4px)",
            display: "flex", alignItems: "center", gap: 5, justifyContent: "flex-end",
          }}>
            📖 {currentIndex + 1} / {CHAPTERS.length}
          </div>
        </header>

        {/* ── Left page: chapter number + emblem ── */}
        <div style={{
          position: "absolute",
          left: "7%", top: "17%",
          width: "34%", height: "62%",
          display: "flex", flexDirection: "column",
          alignItems: "center", justifyContent: "center",
          gap: 12, pointerEvents: "none",
          opacity: flipping ? 0 : 1, transition: "opacity 0.25s",
        }}>
          <div style={{
            fontFamily: "'Cinzel', serif", fontSize: "clamp(0.55rem, 1.2vw, 0.72rem)",
            color: "#7a5a28", letterSpacing: "0.2em",
            display: "flex", alignItems: "center", gap: 6,
          }}>
            <span style={{ opacity: 0.5 }}>✦</span>
            {`Chapter ${chapter.id} · Week ${chapter.week}`}
            <span style={{ opacity: 0.5 }}>✦</span>
          </div>

          <div style={{ fontSize: "clamp(2.5rem, 5vw, 4rem)" }}>{chapter.emblem}</div>

          <div style={{
            fontFamily: "'Lora', Georgia, serif", fontStyle: "italic",
            fontSize: "clamp(0.65rem, 1.3vw, 0.82rem)",
            color: "#5a3a10", textAlign: "center", lineHeight: 1.5,
            maxWidth: "80%",
          }}>
            {chapter.subtitle}
          </div>

          <OrnamentDivider />

          {/* Fox sway */}
          <div style={{
            fontSize: "clamp(2rem, 4vw, 3rem)",
            animation: "foxSway 5s ease-in-out infinite",
            transformOrigin: "bottom center",
            filter: "drop-shadow(0 4px 10px rgba(0,0,0,0.4))",
          }}>
            🦊
          </div>
        </div>

        {/* ── Right page: story text ── */}
        <div className="sb-page-content" key={currentIndex} style={{
          position: "absolute",
          right: "7%", top: "17%",
          width: "36%", height: "66%",
          display: "flex", flexDirection: "column",
          alignItems: "center", justifyContent: "flex-start", paddingTop: "clamp(10px, 2vh, 20px)",
          padding: "clamp(16px, 3vh, 28px) clamp(12px, 2vw, 24px)",
          overflowY: "auto",
          opacity: flipping ? 0 : 1, transition: "opacity 0.25s",
          // Scrollbar styling
          scrollbarWidth: "thin",
          scrollbarColor: "rgba(140,100,40,0.3) transparent",
        }}>

          {/* Chapter title */}
          <div style={{
            fontFamily: "'Cinzel', serif", fontSize: "clamp(0.55rem, 1.1vw, 0.68rem)",
            color: "#8a6a3a", letterSpacing: "0.18em",
            display: "flex", alignItems: "center", gap: 6, marginBottom: 8,
          }}>
            <span style={{ opacity: 0.6 }}>✦</span>
            {`Chapter ${chapter.id}`}
            <span style={{ opacity: 0.6 }}>✦</span>
          </div>

          <h2 style={{
            fontFamily: "'Cinzel Decorative', 'Cinzel', serif",
            fontSize: "clamp(0.9rem, 2.2vw, 1.35rem)",
            color: "#3d1f00", margin: "0 0 10px", fontWeight: 700,
            lineHeight: 1.2, textAlign: "center",
            textShadow: "0 1px 4px rgba(200,140,40,0.18)",
          }}>
            {chapter.title}
          </h2>

          <OrnamentDivider />

          {/* Paragraphs */}
          <div style={{
            display: "flex", flexDirection: "column",
            gap: "clamp(6px, 1.2vh, 10px)",
            margin: "12px 0",
          }}>
            {isGenerating ? (
              <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 10, padding: "16px 0" }}>
                <div style={{ display: "flex", gap: 7 }}>
                  {[0, 1, 2].map((i) => (
                    <div key={i} style={{
                      width: 7, height: 7, borderRadius: "50%", background: "#8a6a3a",
                      animation: `storyDot 0.9s ${i * 0.15}s ease-in-out infinite`,
                    }} />
                  ))}
                </div>
                <p style={{ fontFamily: "'Lora', Georgia, serif", fontSize: "0.72rem", color: "#6a4a20", fontStyle: "italic", margin: 0 }}>
                  Weaving your story…
                </p>
              </div>
            ) : (
              displayParagraphs.map((p, i) => (
                <p key={i} style={{
                  fontFamily: "'Lora', Georgia, serif",
                  fontSize: "clamp(0.68rem, 1.4vw, 0.82rem)",
                  color: "#4a3010", lineHeight: 1.68,
                  margin: 0, textAlign: "center",
                }}>
                  {p}
                </p>
              ))
            )}
          </div>

          {/* Generate button */}
          {!aiParagraphs && !isGenerating && logs.length >= 3 && (
            <button onClick={handleGenerate} style={{
              marginBottom: 10,
              background: "rgba(140,100,40,0.1)",
              border: "1px solid rgba(140,100,40,0.3)",
              borderRadius: 20, padding: "5px 14px",
              fontFamily: "'Cinzel', serif", fontSize: "0.6rem",
              letterSpacing: "0.08em", color: "#6a4a20",
              cursor: "pointer",
            }}>
              ✦ Generate Story
            </button>
          )}

          <OrnamentDivider />

          {/* Quote box */}
          <div style={{
            display: "flex", alignItems: "center", gap: 8,
            background: "rgba(180,130,40,0.08)",
            border: "1px solid rgba(140,100,40,0.2)",
            borderRadius: 6, padding: "8px 10px",
            width: "100%", marginTop: 8,
          }}>
            <span style={{ fontSize: "clamp(1rem, 2vw, 1.3rem)", flexShrink: 0 }}>🦊</span>
            <p style={{
              fontFamily: "'Lora', Georgia, serif", fontStyle: "italic",
              fontSize: "clamp(0.6rem, 1.2vw, 0.72rem)",
              color: "#5a3a10", margin: 0, lineHeight: 1.5, textAlign: "center",
            }}>
              "{chapter.quote}"
            </p>
          </div>
        </div>

        {/* ── Navigation ── */}
        <nav style={{
          position: "absolute", bottom: 0, left: 0, right: 0,
          display: "flex", alignItems: "center", justifyContent: "center",
          gap: "clamp(8px, 2vw, 16px)",
          padding: "10px 20px 14px", zIndex: 30,
        }}>
          <button
            onClick={() => currentIndex > 0 && triggerFlip(currentIndex - 1)}
            disabled={currentIndex === 0}
            style={{
              background: "rgba(18,10,3,0.85)", border: "1px solid rgba(200,168,75,0.4)",
              borderRadius: 50, color: currentIndex === 0 ? "rgba(180,150,80,0.3)" : "#c8a84b",
              fontFamily: "'Cinzel', serif", fontSize: "0.68rem", letterSpacing: "0.08em",
              padding: "7px 20px", cursor: currentIndex === 0 ? "default" : "pointer",
              backdropFilter: "blur(6px)", boxShadow: "0 4px 16px rgba(0,0,0,0.4)",
            }}
          >
            ‹ Previous
          </button>

          <div style={{
            background: "rgba(18,10,3,0.85)", border: "1px solid rgba(200,168,75,0.3)",
            borderRadius: 50, color: "#c8a84b",
            fontFamily: "'Cinzel', serif", fontSize: "0.65rem", letterSpacing: "0.1em",
            padding: "7px 20px", backdropFilter: "blur(6px)",
            display: "flex", alignItems: "center", gap: 7,
          }}>
            <span style={{ opacity: 0.6 }}>🌿</span>
            {currentIndex + 1} / {CHAPTERS.length}
            <span style={{ opacity: 0.6 }}>🌿</span>
          </div>

          <button
            onClick={() => currentIndex < CHAPTERS.length - 1 && triggerFlip(currentIndex + 1)}
            disabled={currentIndex === CHAPTERS.length - 1}
            style={{
              background: "rgba(18,10,3,0.85)", border: "1px solid rgba(200,168,75,0.4)",
              borderRadius: 50, color: currentIndex === CHAPTERS.length - 1 ? "rgba(180,150,80,0.3)" : "#c8a84b",
              fontFamily: "'Cinzel', serif", fontSize: "0.68rem", letterSpacing: "0.08em",
              padding: "7px 20px", cursor: currentIndex === CHAPTERS.length - 1 ? "default" : "pointer",
              backdropFilter: "blur(6px)", boxShadow: "0 4px 16px rgba(0,0,0,0.4)",
            }}
          >
            Next ›
          </button>
        </nav>

      </div>
    </>
  );
}
